### PR TITLE
Migrate maps section to sf

### PR DESCRIPTION
**Pull request by dieghernan**
See #95

### CODE REVIEW

**Comment by holtzy** [comment]
thank you SO MUCH for this. I'll review next Monday. 🙏

**Comment by holtzy** [comment]
Sorry I'm swamped. This is planned for next Monday. Thanks again!!!!!

**Comment by holtzy** [comment]
@JosephBARBIERDARNAL to remind me next Monday

**Comment by holtzy** [comment]
Merged through https://github.com/holtzy/R-graph-gallery/pull/175 because of conflicts.

Thank you SO MUCH for your work 🙏

**Comment by kadyb** [comment]
@dieghernan great job!

**Pull request merged**
