### PR TITLE
topr PR

### PR DESCRIPTION
**Pull request by totajuliusd**

### CODE REVIEW

**Comment by holtzy** [comment]
@JosephBARBIERDARNAL we should try to prioritise this.
@totajuliusd  sorry for the delay

**Comment by JosephBARBIERDARNAL** [comment]
Hi @totajuliusd ! thanks for your work!

In order to merge this PR, could you add another commit where you discard your changes in `template_rgg.html`?

**Comment by totajuliusd** [comment]
Hi Joseph,

Of course, I will do that. I might then also use the chance to update the
PR a bit too since there have been some minor changes to topr which might
be nice to include.

Tota

**Comment by JosephBARBIERDARNAL** [comment]
perfect, thanks again! 🙏

**Pull request closed without merging**
